const bcrypt = require("bcryptjs");

const { ROLES } = require("../../config/roles");

async function createSeedData() {
  const defaultPassword = await bcrypt.hash("Password123!", 10);

  return {
    counters: {
      user: 7,
      appointment: 5,
      prescription: 3,
      rating: 1,
      supportTicket: 3,
      medicine: 4,
    },
    users: [
      {
        id: 1,
        name: "Dr. Ayesha Khan",
        email: "doctor@mediflow.com",
        phone: "03001234567",
        role: ROLES.DOCTOR,
        passwordHash: defaultPassword,
        cnic: "35202-1111111-1",
        dob: "1988-04-12",
        maritalStatus: "Married",
        isActive: true,
        profile: {
          specialization: "Cardiology",
          experience: "9 years",
          timing: "09:00 AM - 03:00 PM",
          department: "Cardiology",
        },
      },
      {
        id: 2,
        name: "Dr. Hamza Ali",
        email: "doctor2@mediflow.com",
        phone: "03007654321",
        role: ROLES.DOCTOR,
        passwordHash: defaultPassword,
        cnic: "35202-2222222-2",
        dob: "1985-09-18",
        maritalStatus: "Single",
        isActive: true,
        profile: {
          specialization: "Neurology",
          experience: "12 years",
          timing: "02:00 PM - 08:00 PM",
          department: "Neurology",
        },
      },
      {
        id: 3,
        name: "Sara Ahmed",
        email: "patient@mediflow.com",
        phone: "03111234567",
        role: ROLES.PATIENT,
        passwordHash: defaultPassword,
        cnic: "35202-3333333-3",
        dob: "1997-02-05",
        maritalStatus: "Single",
        isActive: true,
        profile: {
          age: 28,
          blood: "B+",
        },
      },
      {
        id: 4,
        name: "Bilal Hussain",
        email: "patient2@mediflow.com",
        phone: "03117654321",
        role: ROLES.PATIENT,
        passwordHash: defaultPassword,
        cnic: "35202-4444444-4",
        dob: "1990-06-22",
        maritalStatus: "Married",
        isActive: true,
        profile: {
          age: 35,
          blood: "A-",
        },
      },
      {
        id: 5,
        name: "Fatima Noor",
        email: "staff@mediflow.com",
        phone: "03211234567",
        role: ROLES.STAFF,
        passwordHash: defaultPassword,
        cnic: "35202-5555555-5",
        dob: "1993-11-14",
        maritalStatus: "Single",
        isActive: true,
        profile: {
          department: "Front Desk",
          shift: "Morning",
        },
      },
      {
        id: 6,
        name: "Usman Tariq",
        email: "staff2@mediflow.com",
        phone: "03217654321",
        role: ROLES.STAFF,
        passwordHash: defaultPassword,
        cnic: "35202-6666666-6",
        dob: "1992-12-01",
        maritalStatus: "Married",
        isActive: false,
        profile: {
          department: "Records",
          shift: "Evening",
        },
      },
    ],
    appointments: [
      {
        id: 1,
        patientId: 3,
        doctorId: 1,
        date: "2026-05-05T10:00:00.000Z",
        reason: "Routine checkup",
        status: "scheduled",
        rated: false,
      },
      {
        id: 2,
        patientId: 4,
        doctorId: 1,
        date: "2026-05-03T12:30:00.000Z",
        reason: "Chest pain review",
        status: "admitted",
        rated: false,
      },
      {
        id: 3,
        patientId: 3,
        doctorId: 2,
        date: "2026-04-20T15:00:00.000Z",
        reason: "Migraine follow-up",
        status: "completed",
        rated: false,
      },
      {
        id: 4,
        patientId: 4,
        doctorId: 2,
        date: "2026-04-10T09:00:00.000Z",
        reason: "Neurology consult",
        status: "completed",
        rated: true,
      },
    ],
    prescriptions: [
      {
        id: 1,
        patientId: 4,
        doctorId: 1,
        medicine: "Aspirin",
        dosage: "1 tablet after breakfast",
        createdAt: "2026-04-30T09:30:00.000Z",
      },
      {
        id: 2,
        patientId: 3,
        doctorId: 2,
        medicine: "Sumatriptan",
        dosage: "50mg when symptoms begin",
        createdAt: "2026-04-21T10:30:00.000Z",
      },
    ],
    ratings: [
      {
        id: 1,
        appointmentId: 4,
        doctorId: 2,
        patientId: 4,
        rating: 5,
        createdAt: "2026-04-10T10:00:00.000Z",
      },
    ],
    medicines: [
      { id: 1, name: "Aspirin", stock: 120 },
      { id: 2, name: "Paracetamol", stock: 200 },
      { id: 3, name: "Insulin", stock: 40 },
      { id: 4, name: "Amoxicillin", stock: 75 },
    ],
    supportTickets: [
      { id: 1, userId: 3, message: "Need help downloading my report.", status: "Pending" },
      { id: 2, userId: 4, message: "Appointment time needs confirmation.", status: "Resolved" },
      { id: 3, userId: 1, message: "Prescription page loads slowly.", status: "Pending" },
    ],
  };
}

module.exports = { createSeedData };
