/*class RatingRepository {
  constructor(db) {
    this.db = db;
  }

  //findByDoctorId(doctorId) {
  //  return this.database.ratings.filter((item) => item.doctorId === Number(doctorId));
    //}
    async findByDoctorId(doctorId) {
        const [rows] = await this.db.query(
            "SELECT * FROM ratings WHERE doctor_id = ?",
            [Number(doctorId)]
        );
        return rows || [];
    }

  findByAppointmentId(appointmentId) {
    return this.database.ratings.find((item) => item.appointmentId === Number(appointmentId)) || null;
  }

  create(rating) {
    this.db.ratings.push(rating);
    return rating;
  }
}

module.exports = { RatingRepository };*/

class RatingRepository {
    constructor(db) {
        this.db = db;
    }

    async findByDoctorId(doctorId) {
        const [rows] = await this.db.query(
            `SELECT r.*
             FROM ratings r
             JOIN doctors d ON d.user_id = r.doctor_id OR d.id = r.doctor_id
             WHERE d.user_id = ?`,
            [Number(doctorId)]
        );
        return rows || [];
    }

    async findByAppointmentId(appointmentId) {
        const [rows] = await this.db.query(
            "SELECT * FROM ratings WHERE appointment_id = ?",
            [Number(appointmentId)]
        );
        return rows[0] || null;
    }

    async create(ratingData) {
        const query = `
      INSERT INTO ratings (doctor_id, patient_id, appointment_id, rating, comment)
      VALUES (?, ?, ?, ?, ?)
    `;
        const params = [
            ratingData.doctorId,
            ratingData.patientId,
            ratingData.appointmentId,
            ratingData.rating,
            ratingData.comment || ""
        ];

        const [result] = await this.db.query(query, params);

        // Return the new rating with the ID generated by MariaDB
        return { id: Number(result.insertId), ...ratingData };
    }
}

module.exports = { RatingRepository };
